version: 2

jobs:
  build-and-push:
    environment:
      IMAGE_NAME: jadametz/sb-coders-demo
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Publish Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
